version: "3.8"
services:
  kafka:
    image: kafka-elk:latest
    container_name: kafka
    ports:
      - "9092:9092"
    network_mode: "host"

  logstash:
    image: logstash-elk:latest
    container_name: logstash
    volumes:
#      - /e/Workspace/server/logstash/logstash-9.3.2/config:/usr/share/logstash/config
      - /e/Workspace/server/logstash/logstash-9.3.2/config/logstash-elk-kafka.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "9600:9600"
    depends_on:
      - kafka
    network_mode: "host"
